//Pokemon Constants
export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_TYPES = 'GET_TYPES';
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME';
export const FILTER_POKEMONS_BY_TYPES = 'FILTER_POKEMONS_BY_TYPES';
export const SORT_POKEMONS_BY_NAME = 'SORT_POKEMONS_BY_NAME';
export const SORT_POKEMONS_BY_ATTACK = 'SORT_POKEMONS_BY_ATTACK';
export const POKEMONS_LOADING = 'POKEMONS_LOADING';
export const TRUNCATE_POKEMONS = 'TRUNCATE_POKEMONS';
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID';
export const APPLY_FILTERS = 'APPLY_FILTERS';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';

// export const GET_EXISTING_OR_CREATED_POKEMONS = 'GET_EXISTING_OR_CREATED_POKEMONS';

//SearchBar Constants
export const ERROR_MESSAGE_SEARCH_BAR = 'ERROR_MESSAGE_SEARCH_BAR';
export const SEARCHING_SEARCH_BAR = 'SEARCHING_SEARCH_BAR';